---

- name: Install Apache2
  apt:
    name: apache2 
    # update_cache: yes
    state: present
- name: Install PHP module
  apt: 
    name: libapache2-mod-php5 
    state: present
- name: start apache
  service: 
    name: apache2
    state: running
    enabled: yes

- name: install hello world script
  copy: src=index.php dest=/var/www/index.php mode=0664