---
  - name: Change Port
    lineinfile: 
      #dest: /etc/sysconfig/network-scripts/ifcfg-enp0s9 
      dest: /etc/ssh/sshd_config
      #regexp: '^ONBOOT' 
      regexp: '^Port 443'
      line: 'Port 22'
      #line: 'ONBOOT=yes'


#  - name: Restart SSH
#    service: 
#      name: ssh 
#      state: restarted

          # - name: setup selinux for alternate SSH port
          #   seport:
          #     ports: "443"
          #     proto: "tcp"
          #     setype: "ssh_port_t"
          #     state: "present"


        # - name: "install apache"
        #   apt:
        #     name: apache2
        #     state: lastest
